
INSERT IGNORE INTO ingredients (name) VALUES ('dầu');
INSERT IGNORE INTO ingredients (name) VALUES ('hành tím');
INSERT IGNORE INTO ingredients (name) VALUES ('tỏi');
INSERT IGNORE INTO ingredients (name) VALUES ('nước tương');
INSERT IGNORE INTO ingredients (name) VALUES ('nước sốt hàu');
INSERT IGNORE INTO ingredients (name) VALUES ('nước xốt');
INSERT IGNORE INTO ingredients (name) VALUES ('đường');
INSERT IGNORE INTO ingredients (name) VALUES ('Nước');
INSERT IGNORE INTO ingredients (name) VALUES ('tinh bột');
INSERT IGNORE INTO ingredients (name) VALUES ('cơm');
INSERT IGNORE INTO ingredients (name) VALUES ('tấm rong biển nori');
INSERT IGNORE INTO ingredients (name) VALUES ('dưa chuột');
INSERT IGNORE INTO ingredients (name) VALUES ('quả bơ');
INSERT IGNORE INTO ingredients (name) VALUES ('thanh cua');
INSERT IGNORE INTO ingredients (name) VALUES ('cá hồi');
INSERT IGNORE INTO ingredients (name) VALUES ('Masago');
INSERT IGNORE INTO ingredients (name) VALUES ('hành lá');
INSERT IGNORE INTO ingredients (name) VALUES ('gừng');
INSERT IGNORE INTO ingredients (name) VALUES ('sườn dự phòng');
INSERT IGNORE INTO ingredients (name) VALUES ('con tôm');
INSERT IGNORE INTO ingredients (name) VALUES ('gia vị');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt lợn');
INSERT IGNORE INTO ingredients (name) VALUES ('trứng');
INSERT IGNORE INTO ingredients (name) VALUES ('cà chua');
INSERT IGNORE INTO ingredients (name) VALUES ('muối');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt gà');
INSERT IGNORE INTO ingredients (name) VALUES ('bột ngọt');
INSERT IGNORE INTO ingredients (name) VALUES ('tương cà');
INSERT IGNORE INTO ingredients (name) VALUES ('mắm tôm');
INSERT IGNORE INTO ingredients (name) VALUES ('bún gạo');
-- INSERT IGNORE INTO ingredients (name) VALUES ('khối lập phương');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh ngọt');
-- INSERT IGNORE INTO ingredients (name) VALUES ('thân cây');
INSERT IGNORE INTO ingredients (name) VALUES ('Rau xà lách');
INSERT IGNORE INTO ingredients (name) VALUES ('Giá đỗ');
INSERT IGNORE INTO ingredients (name) VALUES ('Chanh');
INSERT IGNORE INTO ingredients (name) VALUES ('Hành lá');
INSERT IGNORE INTO ingredients (name) VALUES ('sườn heo');
INSERT IGNORE INTO ingredients (name) VALUES ('nước mắm');
INSERT IGNORE INTO ingredients (name) VALUES ('Mật ong');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt tiêu đen');
INSERT IGNORE INTO ingredients (name) VALUES ('sả');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt bò');
INSERT IGNORE INTO ingredients (name) VALUES ('đường nâu');
INSERT IGNORE INTO ingredients (name) VALUES ('củ hành');
INSERT IGNORE INTO ingredients (name) VALUES ('bơ');
INSERT IGNORE INTO ingredients (name) VALUES ('rau xà lách');
INSERT IGNORE INTO ingredients (name) VALUES ('thảo mộc');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Tiếng Anh');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Daikon');
INSERT IGNORE INTO ingredients (name) VALUES ('đậu phộng');
INSERT IGNORE INTO ingredients (name) VALUES ('xoài');
INSERT IGNORE INTO ingredients (name) VALUES ('thạch');
-- INSERT IGNORE INTO ingredients (name) VALUES ('ngọc trai');
INSERT IGNORE INTO ingredients (name) VALUES ('sữa');
INSERT IGNORE INTO ingredients (name) VALUES ('nước cốt dừa');
INSERT IGNORE INTO ingredients (name) VALUES ('hành tây');
INSERT IGNORE INTO ingredients (name) VALUES ('rau mùi');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt giống');
INSERT IGNORE INTO ingredients (name) VALUES ('quế');
INSERT IGNORE INTO ingredients (name) VALUES ('bột');
INSERT IGNORE INTO ingredients (name) VALUES ('chanh');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt chuông');
INSERT IGNORE INTO ingredients (name) VALUES ('bắp cải');
INSERT IGNORE INTO ingredients (name) VALUES ('mì Ý');
INSERT IGNORE INTO ingredients (name) VALUES ('bột tỏi');
INSERT IGNORE INTO ingredients (name) VALUES ('phô mai');
INSERT IGNORE INTO ingredients (name) VALUES ('nấm');
INSERT IGNORE INTO ingredients (name) VALUES ('bún');
-- INSERT IGNORE INTO ingredients (name) VALUES ('trắng');
INSERT IGNORE INTO ingredients (name) VALUES ('dầu mè');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Người gói');
INSERT IGNORE INTO ingredients (name) VALUES ('lòng đỏ');
INSERT IGNORE INTO ingredients (name) VALUES ('chiên');
INSERT IGNORE INTO ingredients (name) VALUES ('dưa');
INSERT IGNORE INTO ingredients (name) VALUES ('lòng đỏ trứng');
-- INSERT IGNORE INTO ingredients (name) VALUES ('trích xuất');
INSERT IGNORE INTO ingredients (name) VALUES ('bột mì');
INSERT IGNORE INTO ingredients (name) VALUES ('bột nở');
INSERT IGNORE INTO ingredients (name) VALUES ('cà rốt');
-- INSERT IGNORE INTO ingredients (name) VALUES ('dán');
INSERT IGNORE INTO ingredients (name) VALUES ('nước ngọt');
-- INSERT IGNORE INTO ingredients (name) VALUES ('hồi');
INSERT IGNORE INTO ingredients (name) VALUES ('Rau mùi');
INSERT IGNORE INTO ingredients (name) VALUES ('Húng quế');
INSERT IGNORE INTO ingredients (name) VALUES ('Chanh xanh');
INSERT IGNORE INTO ingredients (name) VALUES ('bí đao');
INSERT IGNORE INTO ingredients (name) VALUES ('sợi mì');
INSERT IGNORE INTO ingredients (name) VALUES ('chảo');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Tàu hơi nước');
-- INSERT IGNORE INTO ingredients (name) VALUES ('giấy');
INSERT IGNORE INTO ingredients (name) VALUES ('đùi gà');
INSERT IGNORE INTO ingredients (name) VALUES ('bột ngũ vị hương');
INSERT IGNORE INTO ingredients (name) VALUES ('cá');
INSERT IGNORE INTO ingredients (name) VALUES ('tép tỏi');
INSERT IGNORE INTO ingredients (name) VALUES ('đường trắng');
INSERT IGNORE INTO ingredients (name) VALUES ('đậu bắp');
INSERT IGNORE INTO ingredients (name) VALUES ('giá đỗ');
INSERT IGNORE INTO ingredients (name) VALUES ('trộn');
INSERT IGNORE INTO ingredients (name) VALUES ('bột gạo');
INSERT IGNORE INTO ingredients (name) VALUES ('tinh bột ngô');
-- INSERT IGNORE INTO ingredients (name) VALUES ('bụng');
INSERT IGNORE INTO ingredients (name) VALUES ('đậu');
-- INSERT IGNORE INTO ingredients (name) VALUES ('daikon');
INSERT IGNORE INTO ingredients (name) VALUES ('Quả dưa chuột');
INSERT IGNORE INTO ingredients (name) VALUES ('đu đủ');
INSERT IGNORE INTO ingredients (name) VALUES ('giấm');
INSERT IGNORE INTO ingredients (name) VALUES ('nước ép');
INSERT IGNORE INTO ingredients (name) VALUES ('bít tết');
INSERT IGNORE INTO ingredients (name) VALUES ('Bánh mì dài');
INSERT IGNORE INTO ingredients (name) VALUES ('phi lê cá');
INSERT IGNORE INTO ingredients (name) VALUES ('riềng');
INSERT IGNORE INTO ingredients (name) VALUES ('thì là');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Giấy gạo');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh quy giòn');
INSERT IGNORE INTO ingredients (name) VALUES ('lá dứa');
INSERT IGNORE INTO ingredients (name) VALUES ('kem');
INSERT IGNORE INTO ingredients (name) VALUES ('xương');
INSERT IGNORE INTO ingredients (name) VALUES ('thảo quả');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Cổ phần');
-- INSERT IGNORE INTO ingredients (name) VALUES ('quả bóng');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt jalapenos');
INSERT IGNORE INTO ingredients (name) VALUES ('Nước sốt hoisin');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt bột');
INSERT IGNORE INTO ingredients (name) VALUES ('Màu xanh lá');
INSERT IGNORE INTO ingredients (name) VALUES ('mì đậu');
INSERT IGNORE INTO ingredients (name) VALUES ('Múi chanh');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt');
INSERT IGNORE INTO ingredients (name) VALUES ('xương cổ');
INSERT IGNORE INTO ingredients (name) VALUES ('mực ống');
INSERT IGNORE INTO ingredients (name) VALUES ('Thịt lợn');
INSERT IGNORE INTO ingredients (name) VALUES ('thận');
INSERT IGNORE INTO ingredients (name) VALUES ('mì');
INSERT IGNORE INTO ingredients (name) VALUES ('hẹ');
INSERT IGNORE INTO ingredients (name) VALUES ('mập');
INSERT IGNORE INTO ingredients (name) VALUES ('Tiêu đen');
INSERT IGNORE INTO ingredients (name) VALUES ('vai');
INSERT IGNORE INTO ingredients (name) VALUES ('cuộn');
INSERT IGNORE INTO ingredients (name) VALUES ('Nước xốt');
INSERT IGNORE INTO ingredients (name) VALUES ('gan');
INSERT IGNORE INTO ingredients (name) VALUES ('rượu');
INSERT IGNORE INTO ingredients (name) VALUES ('Mít');
INSERT IGNORE INTO ingredients (name) VALUES ('Nhãn');
/-- INSERT IGNORE INTO ingredients (name) VALUES ('Một nửa');
INSERT IGNORE INTO ingredients (name) VALUES ('Kem');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt dẻ');
INSERT IGNORE INTO ingredients (name) VALUES ('Muối');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt');
-- INSERT IGNORE INTO ingredients (name) VALUES ('người da trắng');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt tiêu');
INSERT IGNORE INTO ingredients (name) VALUES ('Dầu mè');
INSERT IGNORE INTO ingredients (name) VALUES ('Bột');
INSERT IGNORE INTO ingredients (name) VALUES ('khoai tây');
INSERT IGNORE INTO ingredients (name) VALUES ('súp lơ');
-- INSERT IGNORE INTO ingredients (name) VALUES ('những khối');
INSERT IGNORE INTO ingredients (name) VALUES ('rau chân vịt');
INSERT IGNORE INTO ingredients (name) VALUES ('màu xanh lá');
INSERT IGNORE INTO ingredients (name) VALUES ('Chanh vàng');
INSERT IGNORE INTO ingredients (name) VALUES ('rau xanh');
-- INSERT IGNORE INTO ingredients (name) VALUES ('miếng vừa ăn');
INSERT IGNORE INTO ingredients (name) VALUES ('đậu Hà Lan');
INSERT IGNORE INTO ingredients (name) VALUES ('xúc xích');
-- INSERT IGNORE INTO ingredients (name) VALUES ('hỗn hợp trước');
-- INSERT IGNORE INTO ingredients (name) VALUES ('lót');
-- INSERT IGNORE INTO ingredients (name) VALUES ('đốt ngón tay');
-- INSERT IGNORE INTO ingredients (name) VALUES ('chân');
INSERT IGNORE INTO ingredients (name) VALUES ('gân');
INSERT IGNORE INTO ingredients (name) VALUES ('quả dứa');
INSERT IGNORE INTO ingredients (name) VALUES ('giăm bông');
-- INSERT IGNORE INTO ingredients (name) VALUES ('hoa');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Trắng');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Lá bạc hà');
-- INSERT IGNORE INTO ingredients (name) VALUES ('giấy gói');
INSERT IGNORE INTO ingredients (name) VALUES ('chanh xanh');
-- INSERT IGNORE INTO ingredients (name) VALUES ('tấm');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt đỏ');
-- INSERT IGNORE INTO ingredients (name) VALUES ('giấy gạo');
INSERT IGNORE INTO ingredients (name) VALUES ('Dưa chuột');
INSERT IGNORE INTO ingredients (name) VALUES ('Dứa');
-- INSERT IGNORE INTO ingredients (name) VALUES ('cái túi');
INSERT IGNORE INTO ingredients (name) VALUES ('trầu cau');
-- INSERT IGNORE INTO ingredients (name) VALUES ('nắp');
-- INSERT IGNORE INTO ingredients (name) VALUES ('đen');
INSERT IGNORE INTO ingredients (name) VALUES ('bột hành tây');
INSERT IGNORE INTO ingredients (name) VALUES ('bột ngô');
-- INSERT IGNORE INTO ingredients (name) VALUES ('bột giấy');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt khô');
INSERT IGNORE INTO ingredients (name) VALUES ('quả xoài');
INSERT IGNORE INTO ingredients (name) VALUES ('lá rau mùi');
-- INSERT IGNORE INTO ingredients (name) VALUES ('liên kết');
INSERT IGNORE INTO ingredients (name) VALUES ('ngô');
-- INSERT IGNORE INTO ingredients (name) VALUES ('móng vuốt');
-- INSERT IGNORE INTO ingredients (name) VALUES ('các phần tư');
INSERT IGNORE INTO ingredients (name) VALUES ('Gia vị');
INSERT IGNORE INTO ingredients (name) VALUES ('Trộn');
INSERT IGNORE INTO ingredients (name) VALUES ('nước sốt hoisin');
-- INSERT IGNORE INTO ingredients (name) VALUES ('sắt');
INSERT IGNORE INTO ingredients (name) VALUES ('cánh gà');
INSERT IGNORE INTO ingredients (name) VALUES ('cá da trơn');
-- INSERT IGNORE INTO ingredients (name) VALUES ('Cảnh');
INSERT IGNORE INTO ingredients (name) VALUES ('nước dùng gà');
INSERT IGNORE INTO ingredients (name) VALUES ('thăn bò');
INSERT IGNORE INTO ingredients (name) VALUES ('đinh hương');
INSERT IGNORE INTO ingredients (name) VALUES ('giấm gạo');
INSERT IGNORE INTO ingredients (name) VALUES ('Cải xoong');
INSERT IGNORE INTO ingredients (name) VALUES ('Cà chua');
-- INSERT IGNORE INTO ingredients (name) VALUES ('đồ trang trí');
INSERT IGNORE INTO ingredients (name) VALUES ('đá');
INSERT IGNORE INTO ingredients (name) VALUES ('Giăm bông');
INSERT IGNORE INTO ingredients (name) VALUES ('ức gà');
INSERT IGNORE INTO ingredients (name) VALUES ('màu đỏ');
INSERT IGNORE INTO ingredients (name) VALUES ('dầu ô liu');
INSERT IGNORE INTO ingredients (name) VALUES ('lát hành tây');
INSERT IGNORE INTO ingredients (name) VALUES ('tỏi băm nhỏ');
INSERT IGNORE INTO ingredients (name) VALUES ('nước sốt nướng');
INSERT IGNORE INTO ingredients (name) VALUES ('hoisin_sauce');
INSERT IGNORE INTO ingredients (name) VALUES ('nước nóng');
INSERT IGNORE INTO ingredients (name) VALUES ('masa');
INSERT IGNORE INTO ingredients (name) VALUES ('cơm chín');
INSERT IGNORE INTO ingredients (name) VALUES ('rong biển');
INSERT IGNORE INTO ingredients (name) VALUES ('dưa chua');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt cua');
-- INSERT IGNORE INTO ingredients (name) VALUES ('umeboshi_dán');
INSERT IGNORE INTO ingredients (name) VALUES ('sườn non');
INSERT IGNORE INTO ingredients (name) VALUES ('tôm');
-- INSERT IGNORE INTO ingredients (name) VALUES ('thăn nội');
INSERT IGNORE INTO ingredients (name) VALUES ('trứng đánh tan');
INSERT IGNORE INTO ingredients (name) VALUES ('cà chua thái hạt lựu');
INSERT IGNORE INTO ingredients (name) VALUES ('muối kosher');
INSERT IGNORE INTO ingredients (name) VALUES ('miếng gà');
INSERT IGNORE INTO ingredients (name) VALUES ('men dinh dưỡng');
-- INSERT IGNORE INTO ingredients (name) VALUES ('ớt_dán');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh bông lan');
INSERT IGNORE INTO ingredients (name) VALUES ('hành khô');
-- INSERT IGNORE INTO ingredients (name) VALUES ('rau diếp romaine');
INSERT IGNORE INTO ingredients (name) VALUES ('tôm khô');
INSERT IGNORE INTO ingredients (name) VALUES ('siro cây phong');
-- INSERT IGNORE INTO ingredients (name) VALUES ('chat_masala');
-- INSERT IGNORE INTO ingredients (name) VALUES ('chanh_gras');
-- INSERT IGNORE INTO ingredients (name) VALUES ('chuck');
INSERT IGNORE INTO ingredients (name) VALUES ('bơ tan chảy');
-- INSERT IGNORE INTO ingredients (name) VALUES ('light_rum');
-- INSERT IGNORE INTO ingredients (name) VALUES ('hoagie_roll');
-- INSERT IGNORE INTO ingredients (name) VALUES ('cây ngưu bàng');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt điều');
INSERT IGNORE INTO ingredients (name) VALUES ('mứt');
INSERT IGNORE INTO ingredients (name) VALUES ('quả sung');
INSERT IGNORE INTO ingredients (name) VALUES ('sữa đặc');
INSERT IGNORE INTO ingredients (name) VALUES ('kem dừa');
INSERT IGNORE INTO ingredients (name) VALUES ('quế xay');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt cayenne');
INSERT IGNORE INTO ingredients (name) VALUES ('salad bắp cải');
INSERT IGNORE INTO ingredients (name) VALUES ('mì ống');
INSERT IGNORE INTO ingredients (name) VALUES ('tỏi_muối');
INSERT IGNORE INTO ingredients (name) VALUES ('phô mai cheddar');
-- INSERT IGNORE INTO ingredients (name) VALUES ('mũ nấm');
INSERT IGNORE INTO ingredients (name) VALUES ('mì kiều mạch');
INSERT IGNORE INTO ingredients (name) VALUES ('hành tây vàng');
INSERT IGNORE INTO ingredients (name) VALUES ('dầu ngô');
INSERT IGNORE INTO ingredients (name) VALUES ('dưa lưới');
INSERT IGNORE INTO ingredients (name) VALUES ('vanilla');
INSERT IGNORE INTO ingredients (name) VALUES ('bột nêm');
INSERT IGNORE INTO ingredients (name) VALUES ('cà rốt thái lát');
INSERT IGNORE INTO ingredients (name) VALUES ('sốt cà chua');
INSERT IGNORE INTO ingredients (name) VALUES ('baking_soda');
INSERT IGNORE INTO ingredients (name) VALUES ('húng quế tươi');
INSERT IGNORE INTO ingredients (name) VALUES ('nước cốt chanh');
INSERT IGNORE INTO ingredients (name) VALUES ('bí ngòi spaghetti');
INSERT IGNORE INTO ingredients (name) VALUES ('cơm_mì');
INSERT IGNORE INTO ingredients (name) VALUES ('gạo đỏ');
INSERT IGNORE INTO ingredients (name) VALUES ('idli');
-- INSERT IGNORE INTO ingredients (name) VALUES ('bao bì wonton');
INSERT IGNORE INTO ingredients (name) VALUES ('đá nghiền');
INSERT IGNORE INTO ingredients (name) VALUES ('tỏi nghiền');
-- INSERT IGNORE INTO ingredients (name) VALUES ('trượt băng');
INSERT IGNORE INTO ingredients (name) VALUES ('súp_trộn');
INSERT IGNORE INTO ingredients (name) VALUES ('đậu phụ');
INSERT IGNORE INTO ingredients (name) VALUES ('giấm táo');
INSERT IGNORE INTO ingredients (name) VALUES ('nước chanh');
INSERT IGNORE INTO ingredients (name) VALUES ('sườn_bít_tết');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh mì Pháp');
INSERT IGNORE INTO ingredients (name) VALUES ('ngải giấm');
-- INSERT IGNORE INTO ingredients (name) VALUES ('ritz_cracker');
INSERT IGNORE INTO ingredients (name) VALUES ('lá húng quế');
INSERT IGNORE INTO ingredients (name) VALUES ('kem tươi');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt habanero');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt peperoncino');
INSERT IGNORE INTO ingredients (name) VALUES ('đậu đen');
INSERT IGNORE INTO ingredients (name) VALUES ('não');
INSERT IGNORE INTO ingredients (name) VALUES ('rau mùi tây');
INSERT IGNORE INTO ingredients (name) VALUES ('nhỏ giọt');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt lợn mông');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh mì sandwich');
INSERT IGNORE INTO ingredients (name) VALUES ('gan gà');
INSERT IGNORE INTO ingredients (name) VALUES ('rượu vang trắng');
INSERT IGNORE INTO ingredients (name) VALUES ('dưa lưới mùa đông');
INSERT IGNORE INTO ingredients (name) VALUES ('táo dại');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt mù tạt');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh bao');
INSERT IGNORE INTO ingredients (name) VALUES ('khoai lang');
INSERT IGNORE INTO ingredients (name) VALUES ('bông cải xanh');
INSERT IGNORE INTO ingredients (name) VALUES ('rau bina tươi');
-- INSERT IGNORE INTO ingredients (name) VALUES ('chua cay');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh mì Ý');
INSERT IGNORE INTO ingredients (name) VALUES ('xúc xích chorizo');
INSERT IGNORE INTO ingredients (name) VALUES ('chân bê');
INSERT IGNORE INTO ingredients (name) VALUES ('sò điệp khô');
INSERT IGNORE INTO ingredients (name) VALUES ('miếng dứa');
INSERT IGNORE INTO ingredients (name) VALUES ('mì soba');
-- INSERT IGNORE INTO ingredients (name) VALUES ('thư rác');
INSERT IGNORE INTO ingredients (name) VALUES ('hoa bí ngòi');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt xông khói hun khói');
INSERT IGNORE INTO ingredients (name) VALUES ('húng quế thái');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh mì kẹp');
-- INSERT IGNORE INTO ingredients (name) VALUES ('lapsang_souchong');
INSERT IGNORE INTO ingredients (name) VALUES ('hành tây_muối');
INSERT IGNORE INTO ingredients (name) VALUES ('lúa mì nứt');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt lợn nướng');
INSERT IGNORE INTO ingredients (name) VALUES ('gia vị_muối');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt_ngô');
INSERT IGNORE INTO ingredients (name) VALUES ('bít tết sườn bò');
INSERT IGNORE INTO ingredients (name) VALUES ('cá bơn');
INSERT IGNORE INTO ingredients (name) VALUES ('rau arugula');
INSERT IGNORE INTO ingredients (name) VALUES ('dầu hướng dương');
INSERT IGNORE INTO ingredients (name) VALUES ('tỏi tây');
INSERT IGNORE INTO ingredients (name) VALUES ('tỏi băm');
INSERT IGNORE INTO ingredients (name) VALUES ('đường caster');
INSERT IGNORE INTO ingredients (name) VALUES ('nước lạnh');
INSERT IGNORE INTO ingredients (name) VALUES ('gạo lứt');
INSERT IGNORE INTO ingredients (name) VALUES ('cơm sushi');
INSERT IGNORE INTO ingredients (name) VALUES ('furikake');
INSERT IGNORE INTO ingredients (name) VALUES ('sườn ngắn');
INSERT IGNORE INTO ingredients (name) VALUES ('hải sản');
INSERT IGNORE INTO ingredients (name) VALUES ('masala');
INSERT IGNORE INTO ingredients (name) VALUES ('cừu non');
-- INSERT IGNORE INTO ingredients (name) VALUES ('trứng_lớn');
INSERT IGNORE INTO ingredients (name) VALUES ('cà chua bi');
INSERT IGNORE INTO ingredients (name) VALUES ('muối biển');
-- INSERT IGNORE INTO ingredients (name) VALUES ('bột_ớt_đỏ');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh pound');
INSERT IGNORE INTO ingredients (name) VALUES ('lá rau diếp');
INSERT IGNORE INTO ingredients (name) VALUES ('cá ngừ bào');
INSERT IGNORE INTO ingredients (name) VALUES ('mật mía');
-- INSERT IGNORE INTO ingredients (name) VALUES ('piment_d''espelette');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt bò xay');
INSERT IGNORE INTO ingredients (name) VALUES ('hành tây thái hạt lựu');
INSERT IGNORE INTO ingredients (name) VALUES ('bơ mềm');
INSERT IGNORE INTO ingredients (name) VALUES ('rượu rum trắng');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh mì cuộn ciabatta');
INSERT IGNORE INTO ingredients (name) VALUES ('củ cải');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt');
INSERT IGNORE INTO ingredients (name) VALUES ('mứt cam');
INSERT IGNORE INTO ingredients (name) VALUES ('quất');
INSERT IGNORE INTO ingredients (name) VALUES ('sữa lạnh');
INSERT IGNORE INTO ingredients (name) VALUES ('sữa đậu nành');
-- INSERT IGNORE INTO ingredients (name) VALUES ('garam_masala');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt tiêu xay tươi');
INSERT IGNORE INTO ingredients (name) VALUES ('dưa cải bắp');
INSERT IGNORE INTO ingredients (name) VALUES ('rigatoni');
INSERT IGNORE INTO ingredients (name) VALUES ('phô mai bào sợi');
INSERT IGNORE INTO ingredients (name) VALUES ('nấm hương');
-- INSERT IGNORE INTO ingredients (name) VALUES ('mì_lo_mein');
INSERT IGNORE INTO ingredients (name) VALUES ('hành tây ngọt');
INSERT IGNORE INTO ingredients (name) VALUES ('trứng_luộc_lạnh');
INSERT IGNORE INTO ingredients (name) VALUES ('dưa hấu');
INSERT IGNORE INTO ingredients (name) VALUES ('tinh chất vani');
INSERT IGNORE INTO ingredients (name) VALUES ('súp cà chua');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt hồi');
INSERT IGNORE INTO ingredients (name) VALUES ('hương thảo');
INSERT IGNORE INTO ingredients (name) VALUES ('chanh vàng');
INSERT IGNORE INTO ingredients (name) VALUES ('bí đỏ butternut');
INSERT IGNORE INTO ingredients (name) VALUES ('gạo vàng');
INSERT IGNORE INTO ingredients (name) VALUES ('máy chiên');
INSERT IGNORE INTO ingredients (name) VALUES ('giấy gói trứng cuộn');
INSERT IGNORE INTO ingredients (name) VALUES ('cá rô phi');
-- INSERT IGNORE INTO ingredients (name) VALUES ('đinh hương_tỏi');
INSERT IGNORE INTO ingredients (name) VALUES ('đường hạt');
INSERT IGNORE INTO ingredients (name) VALUES ('đậu nành Nhật Bản');
INSERT IGNORE INTO ingredients (name) VALUES ('hỗn hợp gia vị taco');
INSERT IGNORE INTO ingredients (name) VALUES ('lươn');
INSERT IGNORE INTO ingredients (name) VALUES ('kiwi');
INSERT IGNORE INTO ingredients (name) VALUES ('giấm rượu vang đỏ');
INSERT IGNORE INTO ingredients (name) VALUES ('nước ép trái cây');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt nai');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh mì ciabatta');
-- INSERT IGNORE INTO ingredients (name) VALUES ('ngô_vảy');
-- INSERT IGNORE INTO ingredients (name) VALUES ('pepper_leave');
INSERT IGNORE INTO ingredients (name) VALUES ('kem_nặng');
INSERT IGNORE INTO ingredients (name) VALUES ('hạt nhục đậu khấu');
INSERT IGNORE INTO ingredients (name) VALUES ('canh');
INSERT IGNORE INTO ingredients (name) VALUES ('bột cà ri đỏ');
-- INSERT IGNORE INTO ingredients (name) VALUES ('gia vị old_bay');
INSERT IGNORE INTO ingredients (name) VALUES ('đậu pinto');
INSERT IGNORE INTO ingredients (name) VALUES ('ớt xanh');
-- INSERT IGNORE INTO ingredients (name) VALUES ('sóc');
-- INSERT IGNORE INTO ingredients (name) VALUES ('lưng béo');
INSERT IGNORE INTO ingredients (name) VALUES ('chuck_roast');
-- INSERT IGNORE INTO ingredients (name) VALUES ('sub_roll');
INSERT IGNORE INTO ingredients (name) VALUES ('quả thận');
INSERT IGNORE INTO ingredients (name) VALUES ('rượu sherry');
INSERT IGNORE INTO ingredients (name) VALUES ('củ cải đỏ');
INSERT IGNORE INTO ingredients (name) VALUES ('anh đào có hạt');
INSERT IGNORE INTO ingredients (name) VALUES ('gà_cốt_lết');
INSERT IGNORE INTO ingredients (name) VALUES ('ốc sên');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt viên');
INSERT IGNORE INTO ingredients (name) VALUES ('khoai tây nghiền');
INSERT IGNORE INTO ingredients (name) VALUES ('hoa nhỏ');
-- INSERT IGNORE INTO ingredients (name) VALUES ('rau bina cho bé');
INSERT IGNORE INTO ingredients (name) VALUES ('vỏ bánh');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh mì thủ công');
INSERT IGNORE INTO ingredients (name) VALUES ('xúc xích kielbasa');
INSERT IGNORE INTO ingredients (name) VALUES ('chân cừu');
-- INSERT IGNORE INTO ingredients (name) VALUES ('gốc_lotu');
INSERT IGNORE INTO ingredients (name) VALUES ('quýt');
INSERT IGNORE INTO ingredients (name) VALUES ('raman');
INSERT IGNORE INTO ingredients (name) VALUES ('xúc xích Ý');
INSERT IGNORE INTO ingredients (name) VALUES ('mực nang');
INSERT IGNORE INTO ingredients (name) VALUES ('húng quế');
INSERT IGNORE INTO ingredients (name) VALUES ('xúc xích đánh bóng');
-- INSERT IGNORE INTO ingredients (name) VALUES ('chanh_húng_hương');
INSERT IGNORE INTO ingredients (name) VALUES ('bánh mì brioche');
INSERT IGNORE INTO ingredients (name) VALUES ('hành tây băm nhỏ');
-- INSERT IGNORE INTO ingredients (name) VALUES ('me_bột');
INSERT IGNORE INTO ingredients (name) VALUES ('thịt bò băm nhỏ');
INSERT IGNORE INTO ingredients (name) VALUES ('bỏng ngô');
-- INSERT IGNORE INTO ingredients (name) VALUES ('móc treo bít tết');
INSERT IGNORE INTO ingredients (name) VALUES ('lá rau bina');