-- ==== 1. Dữ liệu bảng ingredients ====
INSERT INTO ingredients (name, description, unit) VALUES
('Bột mì', 'Bột từ lúa mì, dùng làm bánh', 'gram'),
('Đường', 'Đường trắng tinh luyện', 'gram'),
('Muối', 'Muối ăn tinh khiết', 'gram'),
('Dầu ăn', 'Dầu thực vật', 'ml'),
('Trứng gà', 'Trứng gà tươi', 'quả'),
('Sữa tươi', 'Sữa bò nguyên chất', 'ml'),
('Bột nở', 'Bột làm nở bánh', 'gram'),
('Bột cacao', 'Bột cacao nguyên chất', 'gram'),
('Bơ', 'Bơ nhạt', 'gram'),
('Phô mai', 'Phô mai cheddar', 'gram'),
('Thịt gà', 'Thịt gà tươi', 'gram'),
('Thịt bò', 'Thịt bò tươi', 'gram'),
('Hành tây', 'Hành tây trắng', 'gram'),
('Cà chua', 'Cà chua chín đỏ', 'gram'),
('Ớt chuông', 'Ớt chuông đỏ', 'gram'),
('Tỏi', 'Tỏi tươi bóc vỏ', 'gram'),
('Hạt tiêu', 'Hạt tiêu xay', 'gram'),
('Gạo', 'Gạo trắng hạt dài', 'gram'),
('Nước mắm', 'Nước mắm truyền thống', 'ml'),
('Nước tương', 'Nước tương đậm đặc', 'ml');

-- ==== 2. Dữ liệu bảng recipes ====
INSERT INTO recipes (name, instructions, imageurl, cuisine_type, time) VALUES
('Bánh mì sandwich', 'Trộn nguyên liệu, nướng ở 180°C 20 phút', 'https://example.com/sandwich.jpg', 'Vie', 30),
('Bánh ngọt cacao', 'Trộn bột, cacao, nướng 25 phút', 'https://example.com/cake.jpg', 'Vie', 40),
('Súp gà', 'Luộc gà, cho rau củ, nêm gia vị', 'https://example.com/chicken_soup.jpg', 'Vie', 60),
('Cơm rang trứng', 'Rang cơm với trứng và gia vị. Sau do dung ngay. Thuong thuc tron ven', 'https://example.com/fried_rice.jpg', 'Vie', 20),
('Phở bò', 'Ninh xương, chan nước lèo vào bánh phở', 'https://example.com/pho.jpg', 'Vie', 120),
('Salad rau trộn', 'Cắt nhỏ rau, trộn sốt', 'https://example.com/salad.jpg', 'Jap', 15),
('Cơm cà ri Nhật', 'Nấu cà ri, ăn cùng cơm', 'https://example.com/japanese_curry.jpg', 'Jap', 50),
('Mì ramen', 'Nấu nước dùng, luộc mì, cho topping', 'https://example.com/ramen.jpg', 'Jap', 90),
('Sushi cá hồi', 'Cuộn cơm với cá hồi và rong biển', 'https://example.com/sushi.jpg', 'Jap', 45),
('Tempura tôm', 'Tẩm bột, chiên tôm', 'https://example.com/tempura.jpg', 'Jap', 25),
('Bánh bao', 'Nhào bột, gói nhân, hấp 15 phút', 'https://example.com/banhbao.jpg', 'Vie', 35),
('Bún chả', 'Nướng thịt, ăn với bún và rau sống', 'https://example.com/buncha.jpg', 'Vie', 45),
('Canh chua cá', 'Nấu cá với me chua và rau', 'https://example.com/canhchua.jpg', 'Vie', 35),
('Nem rán', 'Cuốn nem, chiên vàng giòn', 'https://example.com/nemran.jpg', 'Vie', 40),
('Chả cá Lã Vọng', 'Chiên cá với thì là', 'https://example.com/chaca.jpg', 'Vie', 30),
('Miso soup', 'Nấu nước dùng, cho miso và đậu phụ', 'https://example.com/miso_soup.jpg', 'Jap', 15),
('Takoyaki', 'Đổ bột vào khuôn, cho bạch tuộc, chiên', 'https://example.com/takoyaki.jpg', 'Jap', 30),
('Onigiri', 'Nặn cơm với nhân cá hoặc umeboshi', 'https://example.com/onigiri.jpg', 'Jap', 20),
('Okonomiyaki', 'Pha bột, chiên bánh với topping', 'https://example.com/okonomiyaki.jpg', 'Jap', 35),
('Matcha cake', 'Trộn bột matcha, nướng 25 phút', 'https://example.com/matcha_cake.jpg', 'Jap', 40);

-- ==== 3. Dữ liệu bảng recipe_ingredients ====
-- Mỗi món ăn sẽ có 3-4 nguyên liệu
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, optional) VALUES
(1, 1, 200, FALSE), (1, 4, 10, FALSE), (1, 5, 2, FALSE),
(2, 1, 150, FALSE), (2, 8, 50, FALSE), (2, 2, 80, FALSE), (2, 7, 5, TRUE),
(3, 11, 300, FALSE), (3, 13, 100, TRUE), (3, 16, 5, FALSE),
(4, 18, 200, FALSE), (4, 5, 1, FALSE), (4, 3, 2, FALSE),
(5, 12, 250, FALSE), (5, 13, 100, FALSE), (5, 16, 5, FALSE),
(6, 14, 100, FALSE), (6, 15, 50, FALSE), (6, 4, 10, TRUE),
(7, 18, 200, FALSE), (7, 14, 100, FALSE), (7, 3, 3, FALSE),
(8, 14, 100, FALSE), (8, 16, 5, FALSE), (8, 15, 50, TRUE),
(9, 18, 100, FALSE), (9, 12, 50, FALSE), (9, 14, 50, TRUE),
(10, 11, 200, FALSE), (10, 1, 100, TRUE), (10, 4, 20, FALSE),
(11, 1, 200, FALSE), (11, 5, 1, FALSE), (11, 9, 50, FALSE),
(12, 12, 200, FALSE), (12, 18, 100, FALSE), (12, 19, 10, TRUE),
(13, 12, 150, FALSE), (13, 14, 100, FALSE), (13, 19, 10, TRUE),
(14, 11, 150, FALSE), (14, 15, 50, FALSE), (14, 3, 3, FALSE),
(15, 12, 150, FALSE), (15, 16, 5, FALSE), (15, 17, 2, FALSE),
(16, 6, 200, FALSE), (16, 20, 10, TRUE), (16, 3, 2, FALSE),
(17, 1, 200, FALSE), (17, 5, 1, FALSE), (17, 12, 50, FALSE),
(18, 18, 100, FALSE), (18, 19, 10, TRUE), (18, 3, 2, FALSE),
(19, 1, 200, FALSE), (19, 4, 20, FALSE), (19, 15, 50, TRUE),
(20, 1, 150, FALSE), (20, 2, 50, FALSE), (20, 6, 100, TRUE);

-- ==== 4. Dữ liệu bảng ingredient_substitutes ====
INSERT INTO ingredient_substitutes (original_ingredient_id, substitute_ingredient_id, similarity_score, comment) VALUES
(1, 7, 0.85, 'Bột nở giúp bánh mềm hơn'),
(2, 19, 0.60, 'Có thể thay đường bằng nước mắm khi làm món mặn'),
(4, 9, 0.70, 'Bơ thay thế dầu ăn trong làm bánh'),
(5, 6, 0.90, 'Sữa có thể thay trứng trong một số công thức chay'),
(8, 2, 0.65, 'Đường thay bột cacao cho vị ngọt'),
(9, 4, 0.75, 'Dầu ăn thay bơ trong nấu ăn'),
(11, 12, 0.80, 'Thịt bò thay thịt gà'),
(12, 11, 0.80, 'Thịt gà thay thịt bò'),
(13, 14, 0.85, 'Cà chua thay hành tây tạo vị ngọt'),
(14, 13, 0.85, 'Hành tây thay cà chua cho món xào'),
(15, 14, 0.70, 'Cà chua đỏ thay ớt chuông'),
(16, 17, 0.90, 'Hạt tiêu thay tỏi để tạo hương thơm'),
(17, 16, 0.90, 'Tỏi thay hạt tiêu'),
(18, 19, 0.80, 'Nước mắm thay nước tương'),
(19, 18, 0.80, 'Nước tương thay nước mắm'),
(2, 6, 0.60, 'Sữa tươi thay đường tạo vị ngọt dịu'),
(3, 20, 0.70, 'Nước tương thay muối'),
(20, 3, 0.70, 'Muối thay nước tương'),
(7, 1, 0.85, 'Bột mì thay bột nở nếu muốn bánh đặc hơn'),
(10, 9, 0.65, 'Bơ thay phô mai trong một số món bánh mặn');
